### ISSUE TITLE
missing the option for App Service plan 

### ISSUE THREAD

**Issue by Pusinato** [Azure/App-Service-Migration-Assistant#9]
#### Investigative information

Please provide the following:

- 2019-05-23 - 12:54:
- Migration Tool App version : Latest
- OS Version:2008 R2

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

**Comment by NitashaV** [comment]
Thanks for the report.  We have a work item to add support for migrating an app to an existing app service plan. we hope to get this fixed in a future release.

At this time, we are always creating a new plan and deploying an app into it.

**Comment by SiddharthPoddar** [comment]
Hi @NitashaV  Please try to release updated release in which we can configure App service plan manually.  by default its create new plan for each application.

**Comment by krolson** [comment]
Hi @SiddharthPoddar and @Pusinato : it is now an option to deploy to an existing dedicated app service plan rather than only creating new ones as of the 1.0.0 release - please open a new issue if you experience any issues with this functionality.

**Comment by karthikaditya** [comment]
I have downloaded the version 1.0.6 of the migration tool, but I still face this issue i.e. The existing app service plan dropdown does not have any options, even though the resource group contains app service plans. PLease see below image

![azure-migration-assitant-blur](https://user-images.githubusercontent.com/16631223/185902286-305e69c0-d9df-4cff-8e81-1345f2cb7b14.png)

**Comment by krolson** [comment]
Hi @karthikaditya,

The tooling currently only supports migration to a _dedicated_ app service plan (for example: Basic, Standard, or Premium SKU) - so while there is an app service plan in that resource group, it is in the Free SKU and not a dedicated SKU. Dedicated means that the web worker VMs running the application are only for apps in your app service plan and no other apps from other customers will run on that VM. There are some features that are only available on dedicated SKUs, and using Free/Shared is mainly recommended for testing and development. It is possible to create a new dedicated app service plan for migration and then scale the SKU to a non-dedicated SKU after migration is complete (though you will not have access to the features that are only available on dedicated SKUs). 

Thanks,
Kristina

**Comment by karthikaditya** [comment]
Thank you, Kristina. 

Updating the app service plan to a dedicated SKU brought the options in the tool and I was able to complete the migration
